### ISSUE TITLE
Destroy old infrastructure after repository restructure is complete. 

### ISSUE THREAD

**Issue by tnation14** [geotrellis/geotrellis-site-deployment#10]
As this repository is being restructured and we add deployment pipelines to [geotrellis-site](https://github.com/geotrellis/geotrellis-site), [geotrellis-chatta-demo](https://github.com/geotrellis/geotrellis-chatta-demo), and [geotrellis-transit](https://github.com/geotrellis/geotrellis-transit), we should aim to incrementally stand up a new environment alongside of the current one. Once the new environment has been completed, import the `geotrellis.io` hosted zone, and run `terraform destroy` against the existing (i.e. old) infrastructure.

**Comment by hectcastro** [comment]
I think that the updated scope for this issue to outline a plan for replacing the existing `geotrellis.io` infrastructure with the one currently associated with `preview.geotrellis.io`. Then, execute the plan.

**Comment by tnation14** [comment]
I think the following plan will work for infrastructure replacement:
- [x] Use `awscli` to make a backup of all current Route 53 records for geotrellis.io.
- [x] `terraform state rm` the geotrellis.io hosted zone from the old remote state config that lives at `s3://aws-state/GT-SITE.tfstate`. This step ensures that geotrellis.io doesn't get destroyed when we run `terraform destroy` on the old state. 
- [x] `terraform import` the geotrellis.io hosted zone into the core remote state.
- [x] Redeploy `geotrellis-site` and `geotrellis-transit` so that the new Route 53 records get created in the geotrellis.io hosted zone.
- [x] `terraform destroy` the old infrastructure.
- [x] Recreate any missing records for geotrellis.io.
